# Generated by Django 2.2.8 on 2023-08-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230808_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
