# Generated by Django 2.2.8 on 2023-08-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230808_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='seen',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
