# Generated by Django 2.2.8 on 2023-08-15 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_ratings_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='rating',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
