# Generated by Django 2.2.8 on 2023-08-15 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_auto_20230815_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=500)),
                ('size', models.CharField(max_length=500)),
                ('color', models.CharField(max_length=500)),
                ('price', models.PositiveIntegerField(default=1)),
                ('total_price', models.PositiveIntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'db_table': 'tbl_cart',
                'managed': True,
            },
        ),
    ]
