# Generated by Django 2.2.8 on 2023-08-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_order_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('percentage', models.PositiveIntegerField(default=1)),
                ('count', models.CharField(max_length=500)),
                ('expiry_date', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'tbl_coupans',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='image',
        ),
    ]
