# Generated by Django 2.2.8 on 2023-08-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20230819_1805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupans',
            old_name='expiry_date',
            new_name='expiry_days',
        ),
        migrations.AddField(
            model_name='coupans',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
