# Generated by Django 2.2.8 on 2023-08-10 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_color_cpde'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='cpde',
            new_name='code',
        ),
    ]
