# Generated by Django 2.2.8 on 2023-08-22 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20230819_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='coupans',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Coupans'),
        ),
        migrations.AddField(
            model_name='product',
            name='run_time_coupan',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
