# Generated by Django 2.2.8 on 2023-08-22 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_cartitem_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Coupans'),
        ),
        migrations.AddField(
            model_name='order',
            name='discounted_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='grand_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
