# Generated by Django 2.2.8 on 2023-08-23 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_remove_product_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='color',
        ),
    ]
