# Generated by Django 2.2.8 on 2023-08-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_remove_orderitems_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='gst',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='gst_amount',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
