# Generated by Django 2.2.8 on 2023-08-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20230824_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gst',
            field=models.CharField(default='18%', max_length=5),
        ),
        migrations.AddField(
            model_name='order',
            name='gst_amount',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
